// Report generation service

import type { Document, Claim, Contradiction, Report, ContradictionReportEntry } from '../types';
import { getClaimStatistics } from './claimExtractor';
import { getContradictionStatistics } from './contradictionDetector';

export function generateReport(
  document: Document,
  claims: Claim[],
  contradictions: Contradiction[]
): Report {
  const claimStats = getClaimStatistics(claims);
  const contradictionStats = getContradictionStatistics(contradictions);

  const contradictionEntries: ContradictionReportEntry[] = contradictions.map(c => ({
    issue: determinePrimaryIssue(c),
    claimA: {
      text: c.claimA.normalizedText,
      citation: c.claimA.citation,
    },
    claimB: {
      text: c.claimB.normalizedText,
      citation: c.claimB.citation,
    },
    type: c.type,
    explanation: c.explanation,
    confidence: c.confidence,
  }));

  const summary = generateExecutiveSummary(document, claims, contradictions, claimStats, contradictionStats);

  return {
    documentId: document.id,
    documentTitle: document.title,
    generatedAt: new Date(),
    summary,
    contradictions: contradictionEntries,
    statistics: {
      totalClaims: claims.length,
      totalContradictions: contradictions.length,
      hardContradictions: contradictionStats.byType.HARD_CONTRADICTION || 0,
      softInconsistencies: contradictionStats.byType.SOFT_INCONSISTENCY || 0,
    },
  };
}

export function exportReportToMarkdown(report: Report): string {
  const md: string[] = [];

  // Header
  md.push(`# Deposition Analysis Report`);
  md.push(`## ${report.documentTitle}`);
  md.push(`Generated: ${report.generatedAt.toLocaleString()}`);
  md.push('');
  md.push('---');
  md.push('');

  // Executive Summary
  md.push(`## Executive Summary`);
  md.push('');
  md.push(report.summary);
  md.push('');

  // Statistics
  md.push(`## Statistics`);
  md.push('');
  md.push(`- **Total Claims Extracted**: ${report.statistics.totalClaims}`);
  md.push(`- **Total Contradictions Found**: ${report.statistics.totalContradictions}`);
  md.push(`- **Hard Contradictions**: ${report.statistics.hardContradictions}`);
  md.push(`- **Soft Inconsistencies**: ${report.statistics.softInconsistencies}`);
  md.push('');

  // Contradictions Table
  if (report.contradictions.length > 0) {
    md.push(`## Contradictions & Inconsistencies`);
    md.push('');

    // Group by issue/topic
    const byIssue = new Map<string, ContradictionReportEntry[]>();
    for (const entry of report.contradictions) {
      if (!byIssue.has(entry.issue)) {
        byIssue.set(entry.issue, []);
      }
      byIssue.get(entry.issue)!.push(entry);
    }

    // Output each issue group
    for (const [issue, entries] of byIssue.entries()) {
      md.push(`### ${issue}`);
      md.push('');

      for (const entry of entries) {
        md.push(`#### ${formatContradictionType(entry.type)} (Confidence: ${(entry.confidence * 100).toFixed(0)}%)`);
        md.push('');
        md.push(`**Statement A** (${entry.claimA.citation}):`);
        md.push(`> ${entry.claimA.text}`);
        md.push('');
        md.push(`**Statement B** (${entry.claimB.citation}):`);
        md.push(`> ${entry.claimB.text}`);
        md.push('');
        md.push(`**Analysis**: ${entry.explanation}`);
        md.push('');
        md.push('---');
        md.push('');
      }
    }
  } else {
    md.push(`## Contradictions & Inconsistencies`);
    md.push('');
    md.push('No contradictions or inconsistencies detected in this deposition.');
    md.push('');
  }

  // Timeline (if available)
  if (report.timeline && report.timeline.length > 0) {
    md.push(`## Timeline`);
    md.push('');

    for (const entry of report.timeline) {
      md.push(`### ${entry.date}`);
      md.push(`**Event**: ${entry.event}`);
      md.push('');
      md.push('**Related Claims**:');
      for (let i = 0; i < entry.claims.length; i++) {
        md.push(`- ${entry.claims[i]} (${entry.citations[i]})`);
      }
      md.push('');
    }
  }

  // Footer
  md.push('---');
  md.push('');
  md.push('*Generated by Legal Deposition Analysis Tool*');
  md.push('');
  md.push('**Disclaimer**: This report is generated by automated analysis and should be reviewed by legal professionals. The tool identifies patterns and potential inconsistencies but does not make legal conclusions.');

  return md.join('\n');
}

export function exportReportToHTML(report: Report): string {
  const md = exportReportToMarkdown(report);

  // Simple markdown to HTML conversion
  let html = md;

  // Headers
  html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');

  // Bold
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

  // Italic
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Blockquotes
  html = html.replace(/^> (.*$)/gm, '<blockquote>$1</blockquote>');

  // Lists
  html = html.replace(/^- (.*$)/gm, '<li>$1</li>');

  // Horizontal rules
  html = html.replace(/^---$/gm, '<hr>');

  // Line breaks
  html = html.replace(/\n\n/g, '</p><p>');
  html = html.replace(/\n/g, '<br>');

  // Wrap in HTML structure
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Deposition Analysis Report - ${report.documentTitle}</title>
  <style>
    body {
      font-family: 'Georgia', serif;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { border-bottom: 3px solid #333; padding-bottom: 10px; }
    h2 { border-bottom: 1px solid #666; padding-bottom: 5px; margin-top: 40px; }
    h3 { color: #555; margin-top: 30px; }
    blockquote {
      border-left: 4px solid #ccc;
      margin-left: 0;
      padding-left: 20px;
      color: #666;
      font-style: italic;
    }
    hr { border: 0; border-top: 1px solid #ccc; margin: 30px 0; }
    li { margin-bottom: 5px; }
    strong { color: #000; }
  </style>
</head>
<body>
  <p>${html}</p>
</body>
</html>
  `.trim();
}

export function exportReportToJSON(report: Report): string {
  return JSON.stringify(report, null, 2);
}

function generateExecutiveSummary(
  document: Document,
  claims: Claim[],
  contradictions: Contradiction[],
  claimStats: any,
  contradictionStats: any
): string {
  const lines: string[] = [];

  lines.push(`This report analyzes the deposition testimony from "${document.title}".`);
  lines.push(`A total of ${claims.length} distinct claims were extracted from ${claims.filter((_, i, arr) => arr.findIndex(c => c.utteranceId === _.utteranceId) === i).length} witness responses.`);

  if (contradictions.length === 0) {
    lines.push(`No significant contradictions or inconsistencies were identified in the testimony.`);
  } else {
    lines.push(`The analysis identified ${contradictions.length} potential contradictions or inconsistencies:`);
    lines.push(`- ${contradictionStats.byType.HARD_CONTRADICTION || 0} hard contradictions (mutually exclusive statements)`);
    lines.push(`- ${contradictionStats.byType.SOFT_INCONSISTENCY || 0} soft inconsistencies (hedging or vagueness)`);
    lines.push(`- ${contradictionStats.byType.SCOPE_SHIFT || 0} scope shifts (changing scope of statements)`);
    lines.push(`- ${contradictionStats.byType.TEMPORAL_CONFLICT || 0} temporal conflicts (timeline inconsistencies)`);
    lines.push(`- ${contradictionStats.byType.DEFINITION_DRIFT || 0} definition drifts (term usage changes)`);
  }

  if (claimStats.topTopics.length > 0) {
    lines.push(`\nKey topics covered: ${claimStats.topTopics.slice(0, 5).map((t: any) => t.topic).join(', ')}.`);
  }

  if (contradictionStats.highConfidence > 0) {
    lines.push(`\n**High Priority**: ${contradictionStats.highConfidence} contradiction(s) have high confidence (≥80%) and should be reviewed carefully.`);
  }

  return lines.join(' ');
}

function determinePrimaryIssue(contradiction: Contradiction): string {
  const topics = new Set([
    ...contradiction.claimA.topics,
    ...contradiction.claimB.topics,
  ]);

  if (topics.size === 0) {
    return 'General Testimony';
  }

  // Capitalize first letter of first topic
  const firstTopic = Array.from(topics)[0];
  return firstTopic.charAt(0).toUpperCase() + firstTopic.slice(1);
}

function formatContradictionType(type: string): string {
  const formatted = type.replace(/_/g, ' ');
  return formatted.charAt(0).toUpperCase() + formatted.slice(1).toLowerCase();
}

export function downloadAsFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function copyToClipboard(content: string): Promise<void> {
  return navigator.clipboard.writeText(content);
}
